# Shadow
shadow          = true;
no-dnd-shadow   = true;
no-dock-shadow  = false;
clear-shadow    = true;
shadow-radius   = 5;
shadow-offset-x = -4;
shadow-offset-y = -4;
shadow-opacity  = 0.25;
shadow-red      = 0.0;
shadow-green    = 0.0;
shadow-blue     = 0.0;
shadow-exclude = [
    "! name ~= ''",
    "name       = '[i3 con] workspace 1'",
    "name       = '[i3 con] workspace 2'",
    "name       = '[i3 con] workspace 3'",
    "name       = '[i3 con] workspace 4'",
    "name       = '[i3 con] workspace 5'",
    "name       = '[i3 con] workspace 6'",
    "name       = '[i3 con] workspace 7'",
    "name       = '[i3 con] workspace 8'",
    "name       = '[i3 con] workspace 9'",
    "name       = '[i3 con] workspace 10'",
    "name       = 'bar'",
    "name       = 'Notification'",
    "class_g    = 'Polybar'",
    "_GTK_FRAME_EXTENTS@:c"
];

# Opacity
menu-opacity                = 0.9;
frame-opacity               = 1;
inactive-opacity-override   = true;
alpha-step                  = 0.06;
blur-background             = true;
blur-background-exclude = [
    "window_type = 'desktop'",
    "_GTK_FRAME_EXTENS@:c"
];

backend = "glx";
refresh-rate = 0;
vsync = "none";

