include-file = $HOME/.config/polybar/colors.ini

include-file = $HOME/.config/polybar/modules/bspwm.ini

; include-file = $HOME/.config/polybar/modules/title.ini
include-file = $HOME/.config/polybar/modules/round-left-blue.ini
include-file = $HOME/.config/polybar/modules/weather.ini
include-file = $HOME/.config/polybar/modules/date.ini
include-file = $HOME/.config/polybar/modules/round-right-blue.ini
; include-file = $HOME/.config/polybar/modules/margin.ini
; include-file = $HOME/.config/polybar/modules/round-right.ini
; include-file = $HOME/.config/polybar/modules/mpd.ini
; include-file = $HOME/.config/polybar/modules/round-left.ini

include-file = $HOME/.config/polybar/modules/memory.ini
include-file = $HOME/.config/polybar/modules/cpu.ini
include-file = $HOME/.config/polybar/modules/pulseaudio.ini
include-file = $HOME/.config/polybar/modules/battery.ini

[bar/main]
monitor = ${env:MONITOR:}

font-0 = "JetBrainsMono Nerd Font:style=Medium:size=14;3"
font-1 = "JetBrainsMono Nerd Font:style=Bold:size=14;3"
font-2 = "JetBrainsMono Nerd Font:size=19;5"

width = 100%
height = 50
offset-y = 0
fixed-center = true
bottom = false
dpi = 192

background = ${colors.semi-trans}
foreground = ${colors.fg}

modules-left = bspwm
modules-center = round-left-blue date round-right-blue 
modules-right = memory cpu pulseaudio battery

tray-backround = ${colors.bg-alt}
tray-padding = 2
tray-position = right
tray-maxsize = 16

[settings]
screenchange-reload = true
